In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3,4]]
x_data = torch.tensor(data)
x_data 

tensor([[1, 2],
        [3, 4]])

In [7]:
np_array = np.array(data)
print(type(np_array))
x_np = torch.from_numpy(np_array)
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [12]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8403, 0.0284],
        [0.7114, 0.5234]]) 



In [18]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Random Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.5070, 0.2283, 0.1491],
        [0.9136, 0.1617, 0.4896]]) 

Random Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [20]:
tensor = torch.rand(3, 4)
print(tensor)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor([[0.8753, 0.7279, 0.3639, 0.5978],
        [0.5005, 0.5502, 0.4170, 0.5236],
        [0.4269, 0.7409, 0.8275, 0.2130]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [38]:
tensor = torch.ones(4, 4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
tensor[:, 1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [25]:
t1 = torch.cat([tensor, tensor, tensor])

In [26]:
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [29]:
print(f" tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor * tensor}")

 tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [41]:
print(f"{tensor}")
print(f"{tensor.T}")
print(f"tensor.matmul(tensor.T) {tensor.matmul(tensor.T)}")
print(f"tensor @ tensor.T {tensor @ tensor.T}")

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor.matmul(tensor.T) tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor @ tensor.T tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [47]:
print(tensor, '\n')
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
